config/routes.rb
Nlcommons::Application.routes.draw do

  resources :attachments
  resources :versions
  resources :collaborator_types

  resources :projects do
    member do
      get 'download'
    end
  end

  match '/browse/model_contents/:dirname/:extensionname.:format' => 'browse#extension'

  match '/browse/:id/model_contents/' => 'browse#model_contents', :as => :model_contents

  match '/browse/:id/:extension/:extension.jar' => 'browse#extension', :as => :extension
  match '/browse/:id/:filename.:format' => 'browse#model_attachment', :as => :model_attachment
  match '/browse/:id/model_contents/:filename.:format' => 'browse#model_contents', :as => :model_attachment

  root :to => 'account#mypage'

  match 'browse/display_preview/:id/:size' => 'browse#display_preview'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  
  attr_accessible :node_id, :person_id, :description, :filename, :content_type, :contents
  
  belongs_to :node
  belongs_to :person

  validates :node_id, :presence => true
  validates :person_id, :presence => true
  validates :description, :presence => true
  validates :filename, :presence => true
  validates :content_type, :presence => true
  validates :contents, :presence => true

  validate :type_must_be_defined

  TYPES = {
    'background' => 'image/png',
    'data' => 'application/x-binary',
    'extension' => 'application/x-binary',
    'gif' => 'image/gif',
    'html' => 'text/html',
    'jpeg' => 'image/jpeg',
    'pdf' => 'application/pdf',
    'png' => 'image/png',
    'powerpoint' => 'application/vnd.ms-powerpoint',
    'preview' => 'image/png',
    'word' => 'application/msword'
  }

  def type_must_be_defined
    errors.add_to_base "The type of this document is undefined" unless TYPES.member?(content_type)
  end

end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  # GET /attachments
  # GET /attachments.xml
  def index
    @attachments = Attachment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @attachments }
    end
  end

  # GET /attachments/1
  # GET /attachments/1.xml
  def show
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @attachment }
    end
  end

  # GET /attachments/new
  # GET /attachments/new.xml
  def new
    @attachment = Attachment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @attachment }
    end
  end

  # GET /attachments/1/edit
  def edit
    @attachment = Attachment.find(params[:id])
  end

  # POST /attachments
  # POST /attachments.xml
  def create
    @attachment = Attachment.new(params[:attachment])

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to(@attachment, :notice => 'Attachment was successfully created.') }
        format.xml  { render :xml => @attachment, :status => :created, :location => @attachment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @attachment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /attachments/1
  # PUT /attachments/1.xml
  def update
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      if @attachment.update_attributes(params[:attachment])
        format.html { redirect_to(@attachment, :notice => 'Attachment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @attachment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.xml
  def destroy
    @attachment = Attachment.find(params[:id])
    @attachment.destroy

    respond_to do |format|
      format.html { redirect_to(attachments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/edit.html.erb
<h1>Editing attachment</h1>

<%= form_for(@attachment) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :node_id %><br />
    <%= f.text_field :node_id %>
  </p>
  <p>
    <%= f.label :person_id %><br />
    <%= f.text_field :person_id %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :contents %><br />
    <%= f.text_field :contents %>
  </p>
  <p>
    <%= f.label :filename %><br />
    <%= f.text_field :filename %>
  </p>
  <p>
    <%= f.label :content_type %><br />
    <%= f.text_field :content_type %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<h1>Listing attachments</h1>

<table>
  <tr>
    <th>Node</th>
    <th>Person</th>
    <th>Description</th>
    <th>Contents</th>
    <th>Filename</th>
    <th>Type</th>
  </tr>

<% @attachments.each do |attachment| %>
  <tr>
    <td><%=h attachment.node_id %></td>
    <td><%=h attachment.person_id %></td>
    <td><%=h attachment.description %></td>
    <td><%=h attachment.contents %></td>
    <td><%=h attachment.filename %></td>
    <td><%=h attachment.content_type %></td>
    <td><%= link_to 'Show', attachment %></td>
    <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
    <td><%= link_to 'Destroy', attachment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New attachment</h1>

<%= form_for(@attachment) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :node_id %><br />
    <%= f.text_field :node_id %>
  </p>
  <p>
    <%= f.label :person_id %><br />
    <%= f.text_field :person_id %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :contents %><br />
    <%= f.text_field :contents %>
  </p>
  <p>
    <%= f.label :filename %><br />
    <%= f.text_field :filename %>
  </p>
  <p>
    <%= f.label :content_type %><br />
    <%= f.text_field :content_type %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p>
  <b>Node:</b>
  <%=h @attachment.node_id %>
</p>

<p>
  <b>Person:</b>
  <%=h @attachment.person_id %>
</p>

<p>
  <b>Description:</b>
  <%=h @attachment.description %>
</p>

<p>
  <b>Contents:</b>
  <%=h @attachment.contents %>
</p>

<p>
  <b>Filename:</b>
  <%=h @attachment.filename %>
</p>

<p>
  <b>Type:</b>
  <%=h @attachment.content_type %>
</p>


<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>