config/routes.rb
Nlcommons::Application.routes.draw do

  resources :attachments
  resources :versions
  resources :collaborator_types

  resources :projects do
    member do
      get 'download'
    end
  end

  match '/browse/model_contents/:dirname/:extensionname.:format' => 'browse#extension'

  match '/browse/:id/model_contents/' => 'browse#model_contents', :as => :model_contents

  match '/browse/:id/:extension/:extension.jar' => 'browse#extension', :as => :extension
  match '/browse/:id/:filename.:format' => 'browse#model_attachment', :as => :model_attachment
  match '/browse/:id/model_contents/:filename.:format' => 'browse#model_contents', :as => :model_attachment

  root :to => 'account#mypage'

  match 'browse/display_preview/:id/:size' => 'browse#display_preview'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/project.rb
# Model to keep track of projects (i.e., collections of models)

class Project < ActiveRecord::Base
  attr_accessible :name, :person

  validates :name, :presence => true, :uniqueness => true

  has_many :node_projects
  has_many :nodes, :through => :node_projects

  belongs_to :person

  default_scope :order => 'lower(name) ASC'
  
  after_save :create_project_image
  
  def create_project_image
    size = 152
    list = Magick::ImageList.new
    if self.nodes.length > 0
      id=self.nodes.fetch(0).id
      self.nodes.each do |model| 
        if !model.preview.blank?
          list.from_blob(model.preview.contents.to_s)
        end
        if list.length  >= 4
          break
        end
      end
    end
    if list.length == 4
      list.each do |image| 
        image.resize_to_fill!(size/2, size/2, Magick::CenterGravity)
      end
      
      m = list.montage {
        self.geometry = "#{size/2}x#{size/2}+0+0"
        self.tile = '2x2'
      } .first
    elsif list.length == 3
      list[0..1].each { |image|
        image.resize_to_fill!(size/2, size/2, Magick::CenterGravity)
      }
      top = list[0..1].montage {
        self.geometry = "#{size/2}x#{size/2}+0+0"
        self.tile = '2x1'
      } .first
      
      bottom = list[2]
      bottom.resize_to_fill!(size, size/2, Magick::CenterGravity)
      list = Magick::ImageList.new
      list.push(top)
      list.push(bottom)
      
      m = list.montage {
        self.geometry = "#{size}x#{size/2}+0+0"
        self.tile = '1x2'
      } .first
    elsif list.length == 2
      list.each do |image| 
        image.resize_to_fill!(size, size/2, Magick::CenterGravity)
      end
      
      m = list.montage {
        self.geometry = "#{size}x#{size/2}+0+0"
        self.tile = '1x2'
      } .first
    elsif list.length == 1
      m = list.first.resize_to_fill!(size, size, Magick::CenterGravity)
    else
      m = Magick::Image.new(1,1) {
        self.background_color = 'rgb(230, 230, 230)'
      }
    end
    
    m.format = 'png'
    dir = Rails.root.to_s + "/public/system/project_images/" + self.id.to_s + "/"
    Dir.mkdir(dir) if !File.exists?(dir)
    m.write(dir + "project.png")
  end
  
  def download_name
    name.gsub(/[\s\/]/, '_')
  end

  def zipfile_name
    "#{download_name}.zip"
  end

  def zipfile_name_full_path
    "#{Rails.root}/public/modelzips/#{zipfile_name}"
  end

  def create_zipfile(web_user)
    Zippy.create zipfile_name_full_path do |io|

      zipped_nodes = [ ]

      nodes.each do |node|
        next unless node.visible_to_user?(web_user)

        zipped_nodes << node
        io["#{download_name}/#{node.download_name}/#{download_name}.nlogo"] = node.contents.to_s

        node.attachments.each do |attachment|
          io["#{download_name}/#{node.download_name}/#{attachment.filename}"] = attachment.contents.to_s
        end

      end

      manifest_string = "Models in the #{name} project\n"

      if zipped_nodes.empty?
        manifest_string << "No models available for download."
      else
        zipped_nodes.each_with_index do |node, index|
          manifest_string << "[%3d]\t" % index
          manifest_string << "Created #{node.created_at}\t"
          manifest_string << "Last updated #{node.updated_at}\t"
          manifest_string << "#{node.id}\t"
          manifest_string << "#{node.name}\t"
          manifest_string << "http://modelingcommons.org/browse/one_model/#{node.id}\n"
        end
      end

      io["MANIFEST"] = manifest_string

    end

    zipfile_name_full_path
  end

end

app/controllers/projects_controller.rb
# Controller to deal witih projects

class ProjectsController < ApplicationController

  before_filter :require_login, :only => [:new, :create, :add_model, :remove_model]

  def index
    @projects = Project.all
    if @person
      @models_to_add = @person.models.select {|model| !model.projects.member?(@project)}.sort_by{|model| model.name.downcase}.map {|model| [model.name, model.id]}
    else
      @models_to_add = []
    end
  end

  def new
  end

  def create
    @project = Project.find_or_create_by_name(:name => params[:project_name],
                                              :person => @person)

    if @project.save
      flash[:notice] = "Successfully created project '#{@project.name}'"
    else
      flash[:notice] = "Could not create the project '#{@project.name}'"
    end

    redirect_to :controller => :account, :action => :mypage
  end

  def show
    @project = Project.find(params[:id])

    if @person
      @models_to_add = @person.models.select {|model| !model.projects.member?(@project)}.sort_by{|model| model.name.downcase}.map {|model| [model.name, model.id]}
    else
      @models_to_add = []
    end
  end

  def find
    render :text => "You are on the 'find' page"
  end

  def add_model
    project = Project.find(params[:project_id])
    model = Node.find(params[:model_id])

    NodeProject.create!(node_id:model.id, project_id:project.id)

    if project.save
      flash[:notice] = "Added model '#{model.name}' to project '#{project.name}'"
    else
      flash[:notice] = "Error adding model '#{model.name}' to project '#{project.name}'"
    end

    redirect_to :controller => :projects, :action => :show, :id => project.id
  end

  def remove_model
    project = Project.find(params[:id])
    model = Node.find(params[:model_id])

    if project.nodes.delete(model)
      flash[:notice] = "Removed model '#{model.name}' from project '#{project.name}'"
    else
      flash[:notice] = "Error removing model '#{model.name}' from project '#{project.name}'"
    end

    redirect_to :controller => :projects, :action => :show, :id => project.id
  end
  
  def download
    project = Project.find(params[:id])
    send_file(project.create_zipfile(@person), :filename => project.zipfile_name, :type => 'application/zip', :disposition => "inline")
  end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def create_project_button
    link_to raw("<button>Create a new project</button>"), :controller => :projects, :action => :new
  end
end

app/views/projects/index.html.erb
<% @title = 'Projects (collections of models)' %>
<% if @person %>
<p><%= create_project_button -%></p>
<% end %>
<% if @projects.empty? %>
<p><i>No projects have been created.</i></p>
<% else %>
<div id="custom_filters">
  Sort by<select id="project_sort_by">
    <option value="pn">Project Name</option>
    <option value="on">Owner Name</option>
    <option value="mc">Model Count</option>
  </select>
  <% if @person %>
  <label for="project_show_you">Show only your projects<input type="checkbox" id="project_show_you" /></label>
  <% end %>
</div>
<table id="projects_table">
  <tbody>
    <% @projects.each do |project| %>
    <tr>
      <td class="shadowbox">
	<div class="project">
	  <div class="heading"><%= project_link(project) -%></div>
	  <div class="contents">
	    <div class="project_image">
	      <a href="<%= project_url(project) -%>"><%= project_image(project) %></a>
	    </div>
	    <div class="project_model_list">
	      <% if project.nodes.length > 0 %>
	        <p><%= link_to "Download project", :controller => :projects, :action => :download, :id => project.id %></p>
	      <% else %>
	        <p>No models in project</p>
	      <% end %>
	      <ul>
      		<% num_projects_to_show = 5%>
      		<% project.nodes[0..(num_projects_to_show - 1)].each do |model| %>
      		<li><%= link_to model.name, model_url(model) -%></li>
      		<% end %>
	      </ul>
	      <% if project.nodes.length > num_projects_to_show %>
	        <p><%= link_to 'And ' << (project.nodes.length - num_projects_to_show).to_s() << ' more', project_url(project) -%></p>
        <% end %>
        
	    </div>
	    <h2><%= link_to (person_image(project.person) + project.person.fullname), person_url(project.person) -%></h2>
	  </div>
	</div>
      </td>
      <td><%= project.name -%></td>
      <td><%= project.person.fullname -%></td>
      <td><%= project.nodes.count -%></td>
      <td>
	<% if project.person == @person %>
	true
	<% else %>
	false
	<% end %>
      </td>
    </tr>
    <% end %>	
  </tbody>
</table>
<% end %>
<% if @person %>
<p><%= create_project_button -%></p>
<% end %>

app/views/projects/new.html.erb
<% @title = "New Project" -%>
<div id="create-project-div" class="project-tab">
  <p>You may create as many projects as you wish.  Each project must have a unique name.</p>

  <%= form_tag :controller => :projects, :action => :create do  %>
      <p><label for="project_name">Name of your new project:</label> <%= text_field_tag "project_name" %></p>
      <p><%= submit_tag "Create project" %></p>
  <% end %>
</div>

app/views/projects/show.html.erb
<% @title = "'#{@project.name}' project" -%>
<div id="project_page">
  <div id="preview_info_container">
    <div id="preview_image">
      <%= project_image(@project) %>
    </div>
    <div id="preview_info">
      <div id="project_owner">
      	<div>
      	  This project is owned by <%= person_link(@project.person) -%> and contains <%= pluralize(@project.nodes.count, "model") -%>
      	</div>
	      <span class="project-download"></span>
      </div>
      <div>
	      <div> 
	        <%= link_to "Download project", :controller => :projects, :action => :download, :id => @project.id %>
	      </div>
      </div>
      <div id="add_model_to_project">
      	<div>
      	  <% if @project.person == @person %>
      	  <% if !@models_to_add.empty? %>
      	  <%= form_tag :controller => :projects, :action => :add_model do  %>
      	  <%= hidden_field_tag :project_id, @project.id -%>
      	  Add one of your models to this project:
      	  <%= select_tag :model_id, options_for_select(@models_to_add)  %>
      	  <%= submit_tag "Add model" %>
      	  <% end %>
      	  <% end %>
      	  <% end %>
      	</div>
      </div>
    </div>
  </div>
  <% if @project.nodes.count.zero? %>
  <p><i>No models in this project.</i></p>
  <% else %>



  <% buttons = Proc.new { |model|
    str = '' 
    if @project.person == @person
    str = link_to raw('<button title="Remove model from project">Remove</button>'), :controller => :projects, :action => :remove_model, :id => @project.id, :model_id => model.id
    end
  str
  } %>
  <h1>Models</h1>
  <%= render :partial => "browse/model_list", :object => @project.nodes, :locals => {:buttons => buttons, :title => 'Project' } %>
  <% end %>
</div>